replication:
  connections:
    - type: postgresql
      uri: postgresql://postgres:postgres@supabase_db_splitpay2:5432/postgres
      sslmode: disable

storage:
  type: postgresql
  uri: postgresql://postgres:postgres@supabase_db_splitpay2:5432/postgres
  sslmode: disable

port: 8080

sync_config:
  path: /config/sync-rules.yaml

client_auth:
  jwks_uri: http://supabase_kong_splitpay2:8000/auth/v1/.well-known/jwks.json
  audience:
    - authenticated
